export const FB_URL = 'https://graph.facebook.com/';
export const ACCESS_TOKEN =
  'EAAZAOiZAFXsyEBALDvNccdeD8wTX6c1dbYPqUsm81wz1AZBW3VvWGZCgQLx8xNiAUGbWYtgZCBY84u6rv9sBbvv2Kxn6xzb0TODGlfKrDZCNUPXC3CfhTOZAAxEZASoVMZBKIp35lijhzxyScyFu7DRVgX7Cb73fTBoOOAq0gHPvyx5gZBJMYeZAh7U';
